openapi: 3.0.1
info:
  title: Plans APIs
  description: API for Plans
  version: 1.1.0
tags: []
paths:
  /api/v1/accounts/{account-id}/subscription-plans:
    get:
      tags:
      - Plans
      summary: Get all subscription plans
      operationId: getAllSubscriptionPlans
      parameters:
      - name: account-id
        in: path
        description: Account id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: searchText
        in: query
        description: Used to search user name
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: next
        in: query
        description: The page number of results
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 1
          default: 1
      - name: limit
        in: query
        description: Used to provide pagination limit for a page
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 10
          default: 10
      responses:
        "200":
          description: successful response
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/SubscriptionPlanListResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/PantherErrorResponse"
        "500":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/PantherErrorResponse"
      security:
      - bearer: []
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
