openapi: 3.0.1
info:
  title: Users APIs
  description: API for Users
  version: 1.1.0
tags: [ ]
paths:
  /api/v1/accounts/{account-id}/users/{user-id}/preferences:
    get:
      tags:
        - Users
      summary: Get User Preferences
      operationId: getUserPreferences
      parameters:
        - name: account-id
          in: path
          description: The ID of the account
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
        - name: user-id
          in: path
          description: The ID of the user
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: preferences
          in: query
          description: The preferences keys to filter
          required: false
          style: form
          explode: true
          allowReserved: true
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/PreferencesResponse"
        "400":
          description: Invalid request parameters
        "500":
          description: Server error
    post:
      tags:
        - Users
      summary: Save User Preferences
      operationId: saveUserPreferences
      parameters:
        - name: account-id
          in: path
          description: The ID of the account
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
        - name: user-id
          in: path
          description: The ID of the user
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "../schema/schemas.yaml#/components/schemas/PreferencesRequest"
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/PreferenceSaveResponse"
        "400":
          description: Invalid request parameters
        "500":
          description: Server error
components:
  schemas: { }
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
