openapi: 3.0.1
info:
  title: Workspaces APIs
  description: API for Workspaces
  version: 1.1.0
tags: []
paths:
  /api/v1/accounts/{account-id}/workspaces:
    get:
      tags:
      - Workspaces
      summary: Get all workspace in an account
      operationId: getWorkspacesByAccountId
      parameters:
      - name: account-id
        in: path
        description: Account id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: searchText
        in: query
        description: Used to search user name
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: next
        in: query
        description: The page number of results
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 1
          default: 1
      - name: limit
        in: query
        description: Used to provide pagination limit for a page
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 10
          default: 10
      - name: ids
        in: query
        description: Used to filter by workspace ids
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      - name: projection
        in: query
        description: Used to get workspace detail projections
        required: false
        style: form
        explode: true
        schema:
          $ref: "../schema/schemas.yaml#/components/schemas/ResponseProjection"
      responses:
        "200":
          description: successful response
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/WorkspacesListResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/PantherErrorResponse"
        "500":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/PantherErrorResponse"
      security:
      - bearer: []
    post:
      tags:
      - Workspaces
      summary: Create a workspace
      operationId: createWorkspace
      parameters:
      - name: account-id
        in: path
        description: The ID of the account
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Create workspace request details
        content:
          application/json:
            schema:
              $ref: "../schema/schemas.yaml#/components/schemas/WorkspaceRequest"
        required: true
      responses:
        "200":
          description: successful response
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/WorkspaceResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/PantherErrorResponse"
        "500":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/PantherErrorResponse"
      security:
      - bearer: []
  /api/v1/accounts/{account-id}/workspaces/{workspace-id}:
    get:
      tags:
      - Workspaces
      summary: Get a workspace in an account
      operationId: getWorkspacesByWorkspaceId
      parameters:
      - name: account-id
        in: path
        description: Account id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: workspace-id
        in: path
        description: The ID of the workspace
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful response
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/WorkspaceDetailResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/PantherErrorResponse"
        "500":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/PantherErrorResponse"
      security:
      - bearer: []
    put:
      tags:
      - Workspaces
      summary: Update a workspace
      operationId: updateWorkspace
      parameters:
      - name: account-id
        in: path
        description: The ID of the account
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: workspace-id
        in: path
        description: The ID of the workspace
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Create workspace request details
        content:
          application/json:
            schema:
              $ref: "../schema/schemas.yaml#/components/schemas/WorkspaceRequest"
        required: true
      responses:
        "200":
          description: successful response
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/WorkspaceResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/PantherErrorResponse"
        "500":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "../schema/schemas.yaml#/components/schemas/PantherErrorResponse"
      security:
      - bearer: []
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
